### ISSUE TITLE
Fix interfaces in core module

### ISSUE THREAD

**Issue by ilkukrisz** [ilkukrisz/SoftwareTesting#10]
After we rethought the core module, the BookService interface should be modified by the followings:

- conatins only listBook method
- new interface: ReaderBookService
- new interface: LibrarianBookService

Both interfaces extend the BookService interface.

Required methods for ReaderBookService:
- [x] requestBook
- [x] showBorrowings
- [x] getAllBooks
- [x] getAllBooksBy........( different filters should be defined ) 

Required methods for LibrarianBookService:
- [x] addBook
- [x] manageBookInstances
- [x] aquireBookInstances
- [x] listBorrowings
- [x] listRequests
- [x] lendBook

**Comment by aron123** [comment]
All OK.
