### ISSUE TITLE
Creation of DTO classes

### ISSUE THREAD

**Issue by ilkukrisz** [ilkukrisz/SoftwareTesting#49]
You should define the basic types in xsd, use plugins in the project to generate the dto-s from them. Notice that, it should be done before the Controller implementation ( issues #43 ), because controller uses these classes to communicate. The task step by step: 
- creation of XSD files.
- adding plugins to generate java classes from xsd ( jaxb2-maven-plugin )

If you have any questions please contact me.

**Comment by aron123** [comment]
#51
